In [ ]:
import tkinter as tk
import mysql.connector 
from tkinter import *
  
def submitact():
     
    user = Username.get()
    passw = password.get()
    data= database.get()

    logintodb(user, passw, data)
  
 
def logintodb(user, passw, data):
     
    # If paswword is enetered by the 
    # user
    if passw:
        db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                     password = passw,
                                     db =data)
        cursor = db.cursor()
         
    # If no password is enetered by the
    # user
    else:
        db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                     data =data)
        cursor = db.cursor()
def databases():
    user = Username.get()
    passw = password.get()
    data= database.get()
    db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                 password = passw,
                                     db =data)
    cursor = db.cursor()
    cursor.execute("SHOW DATABASES")
    i=1
    for student in cursor: 
        for j in range(len(student)):
            e = Entry(root, width=10, fg='black') 
            e.grid(row=i, column=j) 
            e.insert(END, student[j])
            e=Label(root,width=10,text='databases',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=0)
        i=i+1
    db.close()
def first_query():
    user = Username.get()
    passw = password.get()
    data= database.get()
    db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                 password = passw,
                                     db =data)
    cursor = db.cursor()
    cursor.execute("select country_id, country from country where country in ('Afghanistan', 'Bangladesh', 'China');")
    i=1
    for student in cursor: 
        for j in range(len(student)):
            e = Entry(root, width=10, fg='black') 
            e.grid(row=i, column=j) 
            e.insert(END, student[j])
            e=Label(root,width=10,text='country_id',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=0)
            e=Label(root,width=10,text='country',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=1)
               
        i=i+1
    db.close() 
def second_query():
    user = Username.get()
    passw = password.get()
    data= database.get()
    db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                 password = passw,
                                     db =data)
    cursor = db.cursor()
    cursor.execute("select * from actor; alter table actor drop column description; select * from actor;")
    i=1
    for student in cursor: 
        for j in range(len(student)):
            e = Entry(root, width=10, fg='black') 
            e.grid(row=i, column=j) 
            e.insert(END, student[j])
            e=Label(root,width=10,text='actor_id',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=0)
            e=Label(root,width=10,text='first_name',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=1)
            e=Label(root,width=10,text='last_name',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=2)
            e=Label(root,width=10,text='last_update',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=3)
               
        i=i+1
    db.close() 
def third_query():
    user = Username.get()
    passw = password.get()
    data= database.get()
    db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                 password = passw,
                                     db =data)
    cursor = db.cursor()
    cursor.execute("select last_name, count(*) actor_count from actor group by last_name order by actor_count desc, last_name;")
    i=1
    for student in cursor: 
        for j in range(len(student)):
            e = Entry(root, width=10, fg='black') 
            e.grid(row=i, column=j) 
            e.insert(END, student[j])
            e=Label(root,width=10,text='last_name',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=0)
            e=Label(root,width=10,text='actor_count',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=1)
               
        i=i+1
    db.close() 
def fourth_query():
    user = Username.get()
    passw = password.get()
    data= database.get()
    db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                 password = passw,
                                     db =data)
    cursor = db.cursor()
    cursor.execute("select stf.first_name, stf.last_name, sum(pay.amount) from staff stf left join payment pay on stf.staff_id = pay.staff_id WHERE month(pay.payment_date) = 8 and year(pay.payment_date)  = 2005 group by stf.first_name, stf.last_name;")
    i=1
    for student in cursor: 
        for j in range(len(student)):
            e = Entry(root, width=10, fg='black') 
            e.grid(row=i, column=j) 
            e.insert(END, student[j])
            e=Label(root,width=10,text='first_name',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=0)
            e=Label(root,width=10,text='last_name',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=1)
            e=Label(root,width=10,text='sum(pay.amount)',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=2)
        i=i+1
    db.close()    
def fifth_query():
    user = Username.get()
    passw = password.get()
    data= database.get()
    db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                 password = passw,
                                     db =data)
    cursor = db.cursor()
    cursor.execute("select first_name, last_name from actor where actor_id in (select actor_id from film_actor where film_id in (select film_id from film where lower(title) = lower('Alone Trip')));")
    i=1
    for student in cursor: 
        for j in range(len(student)):
            e = Entry(root, width=10, fg='black') 
            e.grid(row=i, column=j) 
            e.insert(END, student[j])
            e=Label(root,width=10,text='first_name',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=0)
            e=Label(root,width=10,text='last_name',borderwidth=1, relief='ridge',anchor='w',bg='yellow')
            e.grid(row=0,column=1)
        i=i+1
    db.close() 
def input_query():
    user = Username.get()
    passw = password.get()
    data= database.get()
    db = mysql.connector.connect(host ="localhost",
                                     user = user,
                                 password = passw,
                                     db = data)
    cursor = db.cursor()
    cursor.execute(savequery1.get())
    i=1 
    for student in cursor: 
        for j in range(len(student)):
            e = Entry(root, width=10, fg='black') 
            e.grid(row=i, column=j) 
            e.insert(END, student[j])    
        i=i+1      
root = tk.Tk()
root.geometry("1100x1000")
root.configure(bg='skyblue')
root.title("DBMS Login Page")
# Definging the first row
welcome = tk.Label(root, text ="Vishnu Kethan Nath's GUI", fg = "white", bg = "skyblue",font = "Helvetica 24 bold italic")
welcome.place(x = 350, y = 20)

lblfrstrow = tk.Label(root, text ="Username:", bg='skyblue',font = "Helvetica 12 bold italic")
lblfrstrow.place(x = 50, y = 50)
 
Username = tk.Entry(root, width = 35)
Username.place(x = 150, y = 50, width = 100)
  
lblsecrow = tk.Label(root, text ="Password:", bg='skyblue',font = "Helvetica 12 bold italic")
lblsecrow.place(x = 50, y = 80)
 
password = tk.Entry(root, width = 35)
password.place(x = 150, y = 80, width = 100)

lblthrdrow = tk.Label(root, text ="Database:", bg='skyblue', font = "Helvetica 12 bold italic")
lblthrdrow.place(x = 50, y = 110)
 
database = tk.Entry(root, width = 35)
database.place(x = 150, y = 110, width = 100)
 
submitbtn = tk.Button(root, text ="Login", font = "Helvetica 12 bold italic",
                      bg ='white', command = submitact)
submitbtn.place(x = 100, y = 150, width = 155)

welcome1 = tk.Label(root, text ="Pre-defined queries:", fg = "white", bg = "skyblue",font = "Helvetica 16 bold italic")
welcome1.place(x = 50, y = 200)

base = tk.Button(root, text ="Databases", font = "Helvetica 12 bold italic",
                      bg ='white', command = databases)
base.place(x = 150, y = 250, width = 155)
one = tk.Button(root, text ="call Afghanistan,Bangladesh,china", font = "Helvetica 12 bold italic",
                      bg ='white', command = first_query)
one.place(x = 150, y = 300, width = 700)
two = tk.Button(root, text ="Delete description of actors", font = "Helvetica 12 bold italic",
                      bg ='white', command = second_query)
two.place(x = 150, y = 350, width = 700)
three = tk.Button(root, text ="List the last names of actors, as well as how many actors have that last name.", font = "Helvetica 12 bold italic",
                      bg ='white', command = third_query)
three.place(x = 150, y = 400, width = 700)
four = tk.Button(root, text ="Total amount rung up by each staff member in August of 2005", font = "Helvetica 12 bold italic",
                      bg ='white', command = fourth_query)
four.place(x = 150, y = 450, width = 700)
five = tk.Button(root, text ="Cast of Alone Trip", font = "Helvetica 12 bold italic",
                      bg ='white', command = fifth_query)
five.place(x = 150, y = 500, width = 700)
welcome1 = tk.Label(root, text ="User-defined queries:", fg = "white", bg = "skyblue",font = "Helvetica 16 bold italic")
welcome1.place(x = 50, y = 600)

query = tk.Label(root, text ="enter the query:", bg='skyblue',font = "Helvetica 14 bold italic"  )
query.place(x = 150, y = 650)
 
savequery1 = tk.Entry(root, width = 35)
savequery1.place(x = 300, y = 650, width = 700)
inputs= tk.Button(root, text ="input ", font = "Helvetica 12 bold italic",
                      bg ='white', command = input_query)
inputs.place(x = 304, y = 700, width = 455)
root.mainloop()